defaults:
  - _default

name: "boostie_data"
_target_: src.datamodules.IEGenericDataModule
batch_size: 2
num_workers: 12

dataset_target_: src.datamodules.IEGenericDataset
data_dir: ${data_dir}/boostie_data

filter_on_num_tokens: True
apply_ordering_heuristic: False
gzipped: False
linearization_class_id: fully_expanded
count_datapoints_with_unk_in_target: False
